config/routes.rb
Rails.application.routes.draw do
  resources :services do 
    resources :reviews
    resources :appointments
  end

  root to: 'services#index'

  get "/appointments" => "appointments#index"

  get '/register' => 'users#new'
  post '/register' => 'users#create'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'

  delete "/logout" => 'sessions#destroy'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/service.rb
class Service < ApplicationRecord
  has_many :reviews, dependent: :destroy
  has_many :appointments, dependent: :destroy
  belongs_to :user
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  include Pagy::Backend

  before_action :set_service, only: [:show, :edit, :update, :destroy]
  before_action :require_login, only: [:create, :update, :destroy, :edit, :new]
  before_action :require_ownership, only: [:update, :edit, :destroy]

  # GET /services
  def index
    if params[:owned].present? 
      if session[:user_id].present?
        @all_services = false
        @pagy, @services = pagy(Service.where(user_id: session[:user_id]).order(created_at: :desc).all)
      else
        flash[:error] = "Must be logged in to see owned services"
        render :index
      end
    else
      @all_services = true
      @pagy, @services = pagy(Service.order(created_at: :desc).all)
    end
  end

  # GET /services/1
  def show
  end

  # GET /services/new
  def new
    @service = Service.new
  end

  # GET /services/1/edit
  def edit
  end

  # POST /services
  def create
    @service = Service.new(service_params)
    @service.user_id = session[:user_id]
    @service.user_name = User.find(session[:user_id]).username

    if @service.save
      redirect_to @service, notice: 'Created service'
    else
      render :new
    end
  end

  # PATCH/PUT /services/1
  def update
    if @service.update(service_params)
      redirect_to @service, notice: 'Updated service'
    else
      render :edit
    end
  end

  # DELETE /services/1
  def destroy
    @service.destroy
    redirect_to services_url, notice: 'Deleted service'
  end

  private
    def require_ownership 
      if @service.user_id != session[:user_id]
        flash[:error] = "Can only edit your own services"
        redirect_to @service
      end
    end

    def set_service
      @service = Service.find(params[:id])
    end

    def service_params
      params.require(:service).permit(:title, :description, :zipcode, :length_of_time, :user_id)
    end
end

app/helpers/services_helper.rb
module ServicesHelper
  include Pagy::Frontend
end

app/views/services/_form.html.erb
<%= form_with(model: service) do |form| %>
  <% if service.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(service.errors.count, "error") %> prohibited this service from being saved:</h2>

      <ul>
        <% service.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :title, class: "control-label" %>
    <%= form.text_field :title, placeholder: "What are you offering?", class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :description, class: "control-label" %>
    <%= form.text_area :description, placeholder: "Some detailed information about your service...", class: "form-control" %>
  </div>

  <div class="actions text-center">
    <%= form.submit class: "btn btn-success" %>
  </div>
<% end %>

app/views/services/edit.html.erb
<h1>Editing Service</h1>

<div class="mx-auto text-center">
    <%= link_to 'Cancel', @service, class: "btn btn-secondary" %>
    <%= link_to 'Delete', @service, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
</div>

<div class='container'>
    <%= render 'form', service: @service %>
</div>

app/views/services/index.html.erb
<h1>Services</h1>

<div class="mx-auto text-center">
  <% if session[:user_id]  %>
    <% if @all_services %>
      <%= link_to 'View my services', services_path(:owned => true), class: "btn btn-secondary" %>
    <% else %>
      <%= link_to 'View all services', services_path, class: "btn btn-secondary" %>    
    <% end %>
    <%= link_to 'Create a service', new_service_path, class: "btn btn-secondary" %>
  <% else %>
    <%= link_to 'Login to create and book services', login_path, class: "btn btn-secondary" %>
  <% end %>  
</div>
<br>

<div class="service-feed">
  <ul class="list-group">
    <% @services.each do |service| %>
      <li class="list-group-item">
        <%= link_to service do %>
          <div class="service-feed-item">
            <div class="service-feed-title">
              <span><%= service.title %></span>            
            </div>
            <div class="service-feed-author">
              <span><%= service.user_name %></span>
            </div>
            <div class="service-feed-created-at">
              <span><%= service.created_at %></span>
            </div>
          </div>
        <% end %>
      </li>
    <% end %>
  </ul>
  <div class="service-feed-nav">
    <%== pagy_bootstrap_nav(@pagy) %>  
  </div>
</div>
<br>

app/views/services/new.html.erb
<% cache_if true do %>
    <p>hi</p>
<h1>New Service</h1>

<div class="mx-auto text-center">
    <%= link_to 'Cancel', services_path, class: "btn btn-secondary" %>
</div>

<div class='container'>
    <%= render 'form', service: @service %>
</div>

<% end %>

app/views/services/show.html.erb
<h1>Service</h1>

<div class="mx-auto text-center">
    <%= link_to 'Back', services_path, class: "btn btn-secondary" %>
    <%= link_to 'See Ratings', service_reviews_url(@service), class: "btn btn-primary" %>
    <% if session[:user_id] == @service.user_id  %>
      <%= link_to 'Edit', edit_service_path(@service), class: "btn btn-primary" %>
      <%= link_to 'Manage Appointments', service_appointments_url(@service), class: "btn btn-primary" %>
    <% elsif session[:user_id] != nil %>
      <%= link_to 'Book Appointment', service_appointments_url(@service), class: "btn btn-primary" %>
    <% end %>
</div>

<div class='service-container container'>
  <div class='service-info'>
    <div class='service-title'>
      <%= @service.title %>
    </div>
    <div class='service-meta'>
      Posted by <span class='service-author'><%= @service.user_name %></span> on <span class='service-created-at'><%= @service.created_at %></span>
    </div>
    <div class='service-description'>
      <%= simple_format(@service.description) %>
    </div>
  </div>
</div>