config/routes.rb
Rails.application.routes.draw do
  resources :services do 
    resources :reviews
    resources :appointments
  end

  root to: 'services#index'

  get "/appointments" => "appointments#index"

  get '/register' => 'users#new'
  post '/register' => 'users#create'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'

  delete "/logout" => 'sessions#destroy'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :service
  belongs_to :user, optional: true
end

app/controllers/appointments_controller.rb
include Pagy::Backend

class AppointmentsController < ApplicationController
  before_action :set_appointment, only: [:update, :destroy]
  before_action :set_service, only: [:new, :create, :destroy, :update]
  before_action :require_login, only: [:index, :update, :destroy, :new]
  before_action :require_ownership, only: [:update, :destroy]
  before_action :require_service_ownership, only: [:new, :create]

  # GET /appointments
  def index
    now = Time.now
    if params[:service_id] != nil
      set_service()
      # Available appointments to book
      @pagy_appointments, @appointments = pagy(
        Appointment
          .where(user_id: nil, service_id: @service.id)
          .where('start_time >= ?', now)
          .order(:date, :start_time),
        page_param: :page_appts
      )
      # Appointments already booked by clients
      @pagy_booked, @booked = pagy(
        Appointment
          .where(service_id: @service.id)
          .where.not(user_id: nil)
          .where('start_time >= ?', now)
          .order(:date, :start_time),
        page_param: :page_booked
      )
    elsif params[:view] == "provider"
      # Available appointment slots for services belonging to user
      @pagy_appointments, @appointments = pagy(
        Appointment
          .where(user_id: nil)
          .where(provider_id: session[:user_id])
          .where('start_time >= ?', now)
          .order("appointments.date", "appointments.start_time"),
        page_param: :page_appts
      )
      # Appointments to services belonging to the current user
      @pagy_booked, @booked = pagy(
        Appointment
          .where.not(user_id: nil)
          .where(provider_id: session[:user_id])
          .where('start_time >= ?', now)
          .order("appointments.date", "appointments.start_time"),
        page_param: :page_booked
      )
    else 
      # Appointments that the current user has made
      @pagy_appointments_future, @appointments_future = pagy(
        Appointment
          .where(user_id: session[:user_id])
          .where('start_time >= ?', now)
          .order(:date, :start_time),
        page_param: :page_appts_future
      )
      @pagy_appointments_past, @appointments_past = pagy(
        Appointment
          .where(user_id: session[:user_id])
          .where('start_time < ?', now)
          .order(date: :desc, start_time: :desc),
        page_param: :page_appts_past
      )
    end
  end

  # GET /appointments/new
  def new 
    @appointment_builder = AppointmentBuilder.new
  end


  # POST /appointments
  def create
    @appointments=[]
    @appointment_builder = AppointmentBuilder.new(appointment_builder_params)
    if !(@appointment_builder.valid?)
      render :new
      return
    end

    date = Time.parse(appointment_builder_params[:date], "%Y-%m-%d")
    duration_mins = appointment_builder_params[:duration].to_i * 60

    start_h, start_m = appointment_builder_params[:start_time].split('.').map(&:to_i)
    end_h, end_m = appointment_builder_params[:end_time].split('.').map(&:to_i)

    start_time = date.change({hour: start_h, min: start_m}) + 8*60*60
    end_time = date.change({hour: end_h, min: end_m}) + 8*60*60

    # @appointment_arr.errors.add(:date, "wasn't filled in")
    # redirect_to service_appointments_url(@service), error: 'Test'

    curr_time = start_time
    while curr_time <= end_time - duration_mins
      appt = Appointment.new(
        date: curr_time,
        start_time: curr_time,
        end_time: curr_time + duration_mins,
        service_id: @service.id,
        provider_id: @service.user_id,
        provider_name: @service.user_name,
        service_title: @service.title
      )
      @appointments << appt
      if !appt.save
        @appointment_builder.errors.merge!(appt)
      end
      curr_time += duration_mins
    end
    # render json: @appointments
    if @appointment_builder.errors.empty?
      redirect_to service_appointments_url(@service), notice: 'Added appointment slots'
    else
      render :new
    end
  end

  # PATCH/PUT /appointments/1
  def update
    case params[:do_action]
      in "decline"
        # Service provider declines a user's appointment, provider redirected to original page
        @appointment.update(user_id: nil)
        @appointment.update(user_name: nil)
        redirect_to request.referer, notice: 'Appointment was declined.'
      in "cancel"
        # User cancels an appointment, user redirected to My appointments page
        @appointment.update(user_id: nil)
        @appointment.update(user_name: nil)
        redirect_to appointments_url, notice: 'Appointment was canceled.'
      in "book"
        @appointment.update(user_id: session[:user_id])
        binding.pry
        @appointment.update(user_name: session[:username])
        if (params[:reschedule] != nil)
          appointment = Appointment.find(params[:reschedule])
          appointment.update(user_id: nil)
          appointment.update(user_name: nil)
        end
        redirect_to appointments_url, notice: 'Appointment was successfully booked.'
    else
      flash[:error] = "Invalid action"
      redirect_to request.referer
    end
  end

  # DELETE /appointments/1
  def destroy
    @appointment.destroy
    redirect_to request.referer, notice: 'Appointment was successfully deleted.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_appointment
      @appointment = Appointment.find(params[:id])
    end

    def set_service
      @service = Service.find(params[:service_id])
    end

    def require_ownership
      if params[:do_action] != 'book' && 
        @service.user_id != session[:user_id] && 
        @appointment.user_id != session[:user_id]
        flash[:error] = "Cannot cancel others' appointments"
        redirect_to request.referer
      end
    end

    def require_service_ownership 
      if @service.user_id != session[:user_id] 
        flash[:error] = "Can only edit your own services"
        redirect_to @service
      end
    end

    # Only allow a list of trusted parameters through.
    def appointment_builder_params
      params.require(:appointment_builder).permit(:date, :start_time, :end_time, :duration)
    end
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
  include Pagy::Frontend
end

app/views/appointments/_book.html.erb
<h1>Book Appointment for <%= @service.title %> </h1>

<div class="mx-auto text-center">
  <% if params[:reschedule] == nil %>
    <%= link_to 'Back', @service, class: "btn btn-secondary" %>
  <% else %>
    <%= link_to 'Cancel', request.referer, class: "btn btn-secondary" %>
  <% end %>
</div>

<br> 

<div class="appointments-feed">
  <% if params[:reschedule] != nil %>
    <ul class="list-group">
      <li class="list-group-item border-0">
        <button type="button" class="btn btn-primary btn-lg btn-block" disabled>
          <% curr = Appointment.find(params[:reschedule])%>
          <div class="appointments-feed-date mt-2">
            <span><b> Current Appointment </b></span>            
          </div>
          <%= render 'book_entry', appointment: curr%>
        </button>
      </li>
    </ul>
  <% end %>
  <% if @appointments.empty? %>
    <p> There are no appointments available for this service at the moment. </p>
  <% end %>
  <ul class="list-group">
    <% @appointments.each do |appointment| %>
      <li class="list-group-item border-0">
        <%= link_to service_appointment_path(appointment.service_id, appointment, :do_action => :book, :reschedule => params[:reschedule]), 
          method: :patch, class: "btn btn-outline-primary btn-lg btn-block", data: {confirm: 'Book appointment?'} do %>
          <%= render 'book_entry', appointment: appointment%>
        <% end %>
      </li>
    <% end %>
  </ul>
  <div class="service-feed-nav">
    <%== pagy_bootstrap_nav(@pagy_appointments) %>  
  </div>
</div>

<br>

app/views/appointments/_book_entry.html.erb
<div class="appointments-feed-item">
  <% start_time = appointment.start_time.getlocal('-08:00') %>
  <% end_time = appointment.end_time.getlocal('-08:00') %>
  <% meridian = (start_time.hour < 12 && end_time.hour >=12) %>
  <% date_str = start_time.strftime("%A, %B %-d, %Y") %>
  <% start_time_str = meridian ? start_time.strftime("%l:%M %P") : start_time.strftime("%l:%M") %>
  <% end_time_str = end_time.strftime("%l:%M %P") %>
  <div class="appointments-feed-date">
    <span><%= "#{date_str}" %></span>            
  </div>
  <div class="appointments-feed-date">
    <span><%= "#{start_time_str} - #{end_time_str}" %></span>            
  </div>
</div>

app/views/appointments/_form.html.erb
<%= form_with(model: appointment_builder, url: service_appointments_url(@service)) do |form| %>
  <br>
  <% if appointment_builder.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(appointment_builder.errors.count, "error") %> prohibited appointments from being generated:</h2>

      <ul>
        <% appointment_builder.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= form.label :date, class: "control-label" %>
    <% today = Time.now.getlocal('-08:00').strftime("%Y-%m-%d") %>
    <%= date_field(:appointment_builder, :date, value: appointment_builder.date || today, min: today, class: "form-control") %>
  </div>

  <% now = (Time.now + 1.hours).beginning_of_hour %>
  <% hour_later = now + 3.hours %>  
  <% now_str = now.strftime("%H:%M") %>
  <% hour_later_str = hour_later.strftime("%H:%M") %>
  <div class="form-group">
    <%= form.label :start_time, class: "control-label" %>
    <%= time_field(:appointment_builder, :start_time, value: appointment_builder.start_time || now_str, include_seconds: false, class: "form-control") %>
  </div>

  <div class="form-group">
    <%= form.label :end_time, class: "control-label" %>
    <%= time_field(:appointment_builder, :end_time, value: appointment_builder.end_time || hour_later_str, include_seconds: false, class: "form-control") %>
  </div>

  <div class="form-group">
    <%= form.label :duration, class: "control-label" %>
    <%= form.select :duration, [["15 minutes", 15], ["30 minutes", 30], ["1 hour", 60], ["2 hours", 120]], {}, { class: "form-control" } %>
  </div>

  <div class="actions text-center">
    <%= form.submit "Generate appointments", class: "btn btn-success" %>
  </div>
<% end %>

app/views/appointments/_list.html.erb
<h1>My Appointments</h1>

<div class="mx-auto text-center">
  <%= link_to 'Switch to Service Provider View', appointments_url(:view => :provider), class: "btn btn-primary" %>
</div>
<br> 

<div class="container-xl">
  <div class="row">
    <div class="col-xl">
      <h3>Upcoming Appointments</h3>
      <% if @appointments_future.empty? %>
        <p class="appointment-empty-message"> You have no upcoming appointments booked for other services. </p>
      <% else %>
        <ul class="list-group">
          <% @appointments_future.each do |appointment| %>
            <li class="list-group-item">
              <%= link_to appointment.service do %>
                <div class="appointment">
                  <%= render 'list_entry', appointment: appointment %>
                  <div class="appointment-buttons">
                    <%= link_to 'Reschedule', 
                      service_appointments_url(appointment.service_id, :reschedule => appointment.id), 
                      class: "btn btn-secondary btn-sm btn-block" %>
                    <%= link_to 'Cancel', 
                      service_appointment_url(appointment.service_id, appointment, :do_action => :cancel), 
                      method: :patch, class: "btn btn-danger btn-sm btn-block",
                      data: {confirm: 'Are you sure you want to cancel this appointment? This will make this appointment slot available to other users.'} %>
                  </div>
                </div>
              <% end %>
            </li>
          <% end %>
        </ul>
        <div class="service-feed-nav">
          <%== pagy_bootstrap_nav(@pagy_appointments_future) %>
        </div>
      <% end %>
    </div>
    <div class="col-xl">
      <h3>Past Appointments</h3>
      <% if @appointments_past.empty? %>
        <p class="appointment-empty-message"> You have no past appointments for other services. </p>
      <% else %>
        <ul class="list-group">
          <% @appointments_past.each do |appointment| %>
            <li class="list-group-item">
              <%= link_to appointment.service do %>
                <div class="appointment">
                  <%= render 'list_entry', appointment: appointment %>
                  <div class="appointment-buttons">
                    <%= link_to 'Add Review', 
                      new_service_review_url(appointment.service), 
                      class: "btn btn-primary btn-sm mt-3 btn-block" %>
                  </div>
                </div>
              <% end %>
            </li>
          <% end %>
        </ul>
        <div class="service-feed-nav">
          <%== pagy_bootstrap_nav(@pagy_appointments_past) %>  
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/appointments/_list_entry.html.erb
<div class="appointment-title">
  <span><%= appointment.service_title %></span>            
</div>
<div class="appointment-author">
  <span>With: <%= appointment.provider_name %></span>          
</div>
<div class="appointment-date">
  <% start_time = appointment.start_time.getlocal('-08:00') %>
  <% end_time = appointment.end_time.getlocal('-08:00') %>
  <% meridian = (start_time.hour < 12 && end_time.hour >=12) %>
  <% date_str = start_time.strftime("%A, %B %-d, %Y") %>
  <% start_time_str = meridian ? start_time.strftime("%l:%M %P") : start_time.strftime("%l:%M") %>
  <% end_time_str = end_time.strftime("%l:%M %P") %>
  <span><%= "#{date_str} • #{start_time_str} - #{end_time_str}" %></span>            
</div>

app/views/appointments/_manage.html.erb
<h1>Manage Appointments</h1>

<div class="mx-auto text-center">
  <% if !params[:service_id].nil? %>
    <%= link_to 'Back', @service, class: "btn btn-secondary" %>
    <%= link_to 'Generate Appointments', new_service_appointment_path(@service), class: "btn btn-primary" %>
  <% else %>
    <%= link_to 'Switch to Client View', appointments_url(), class: "btn btn-primary" %>
  <% end %>
</div>

<br>

<div class="container-xl">
  <div class="row">
    <div class="col-xl">
      <h3>Booked Appointments</h3>
      <% if @booked.empty? %>
        <p class="appointment-empty-message"> 
          There are no booked appointments for <%= params[:service_id] != nil ? "this service" : "your services" %> at the moment. 
        </p>
      <% else %>
        <ul class="list-group">
          <% @booked.each do |appointment| %>
            <li class="list-group-item">
              <% if params[:service_id].nil? %>
                <%= link_to appointment.service do %>
                  <%= render 'manage_booked', appointment: appointment %>
                <% end %>
              <% else %>
                <%= render 'manage_booked', appointment: appointment %>
              <% end %>
            </li>
          <% end %>
        </ul>
        <div class="service-feed-nav">
          <%== pagy_bootstrap_nav(@pagy_booked) %>
        </div>
      <% end %>
    </div>
    <div class="col-xl">
      <h3>Available Appointments</h3>
      <% if @appointments.empty? %>
        <p class="appointment-empty-message"> 
          There are no available appointment slots for <%= params[:service_id] != nil ? "this service" : "your services" %> at the moment. 
        </p>
      <% else %>
        <ul class="list-group">
          <% @appointments.each do |appointment| %>
            <li class="list-group-item">
              <% if params[:service_id].nil? %>
                <%= link_to appointment.service do %>
                  <%= render 'manage_avail', appointment: appointment %>
                <% end %>
              <% else %>
                <%= render 'manage_avail', appointment: appointment %>
              <% end %>
            </li>
          <% end %>
        </ul>
        <div class="service-feed-nav">
          <%== pagy_bootstrap_nav(@pagy_appointments) %>  
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/appointments/_manage_avail.html.erb
<div class="appointment">
  <div class="appointment-title">
    <span><%= appointment.service_title %></span>            
  </div>
  <div class="appointment-date">
    <% start_time = appointment.start_time.getlocal('-08:00') %>
    <% end_time = appointment.end_time.getlocal('-08:00') %>
    <% meridian = (start_time.hour < 12 && end_time.hour >=12) %>
    <% date_str = start_time.strftime("%A, %B %-d, %Y") %>
    <% start_time_str = meridian ? start_time.strftime("%l:%M %P") : start_time.strftime("%l:%M") %>
    <% end_time_str = end_time.strftime("%l:%M %P") %>
    <span><%= "#{date_str} • #{start_time_str} - #{end_time_str}" %></span>            
  </div>
  <div class="appointment-buttons">
    <%= link_to 'Delete', 
      service_appointment_url(appointment.service_id, appointment),
      method: :delete, class: "btn btn-secondary btn-sm mt-3 btn-block",
      data: {confirm: 'Are you sure you want to delete this appointment slot?'} %>
    </div>
</div>

app/views/appointments/_manage_booked.html.erb
<div class="appointment">
  <div class="appointment-title">
    <span><%= appointment.service_title %></span>            
  </div>
  <div class="appointment-author">
    <span>With: <%= appointment.user_name %> </span>            
  </div>
  <div class="appointment-date">
    <% start_time = appointment.start_time.getlocal('-08:00') %>
    <% end_time = appointment.end_time.getlocal('-08:00') %>
    <% meridian = (start_time.hour < 12 && end_time.hour >=12) %>
    <% date_str = start_time.strftime("%A, %B %-d, %Y") %>
    <% start_time_str = meridian ? start_time.strftime("%l:%M %P") : start_time.strftime("%l:%M") %>
    <% end_time_str = end_time.strftime("%l:%M %P") %>
    <span><%= "#{date_str} • #{start_time_str} - #{end_time_str}" %></span>            
  </div>
  <div class="appointment-buttons">
    <%= link_to 'Decline', 
      service_appointment_url(appointment.service_id, appointment, :do_action => :decline),
      method: :patch, class: "btn btn-secondary btn-sm btn-block",
      data: {confirm: 'Are you sure you want to decline this appointment? This appointment slot will become available.'} %>
    <%= link_to 'Delete', 
      service_appointment_url(appointment.service_id, appointment), 
      method: :delete, class: "btn btn-danger btn-sm btn-block",
      data: {confirm: 'Are you sure you want to cancel this appointment? This slot is already booked and will be removed.'} %>
  </div>
</div>

app/views/appointments/book.html.erb
<div class="mx-auto text-center">
  <%= link_to 'Back', @service, class: "btn btn-secondary" %>
  <% if session[:user_id] == @service.user_id  %>
    <%= link_to 'Generate Appointments', new_service_appointment_path(@service), class: "btn btn-primary" %>
  <% end %>
</div>

<div class="service-feed">
  <ul class="list-group">
    <% @appointments.each do |appointment| %>
      <li class="list-group-item">
        <%= link_to appointment, method: :patch, data: {confirm: 'Are you sure?'} do %>
          <div class="appointment-feed-item">
            <div class="appointment-feed-date">
              <span><%= appointment.date.to_s %></span>            
            </div>
            <div class="appointment-feed-start">
              <span><%= appointment.start_time.strftime("%I:%M %p") %></span>
            </div>
            <div class="appointment-feed-end">
              <span><%= appointment.end_time.strftime("%I:%M %p") %></span>
            </div>
          </div>
        <% end %>
      </li>
    <% end %>
  </ul>
</div>

<br>

app/views/appointments/index.html.erb
<% if params[:service_id] != nil %>
  <% if session[:user_id] == @service.user_id  %>
    <%= render 'manage' %>
  <% else %>
    <%= render 'book' %>
  <% end %>
<% elsif params[:view] == 'provider'%>
  <%= render 'manage' %>
<% else %>
  <%= render 'list' %>
<% end %>

app/views/appointments/new.html.erb
<h1>Create Appointments</h1>

<div class="mx-auto text-center">
    <%= link_to 'Cancel', service_appointments_url(@service), class: "btn btn-secondary" %>
</div>

<div class='appointment-builder-container'>
  <% if session[:user_id] != @service.user_id %>
    <div>Not authorized to access resource</div>
  <% else %>
    <%= render 'form', appointment_builder: @appointment_builder %>
  <% end %>
</div>