config/routes.rb
Rails.application.routes.draw do
  resources :services do 
    resources :reviews
    resources :appointments
  end

  root to: 'services#index'

  get "/appointments" => "appointments#index"

  get '/register' => 'users#new'
  post '/register' => 'users#create'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'

  delete "/logout" => 'sessions#destroy'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/reviews_controller.rb
require 'pry'
class ReviewsController < ApplicationController
  include Pagy::Backend

  before_action :set_review, only: [:show, :destroy]
  before_action :set_service, only: [:index, :new, :create]
  before_action :require_login, only: [:index, :destroy, :new]
  before_action :require_ownership, only: [:destroy]

  # GET /services/1/reviews
  def index
    if params[:service_id]
      @pagy, @reviews = pagy(Review.where(service_id: params[:service_id]).order(created_at: :desc).all)
    else
      redirect_to root_path, alert: "Invalid service selected"
    end
  end

  # GET /services/1/reviews/new
  def new
    @review = Review.new
  end

  # POST /reviews
  def create
    @review = Review.new(review_params)
    @review.user_id = current_user.id
    @review.user_name = current_user.username
    @review.service_id = @service.id

    if @review.save
      redirect_to service_reviews_url(@service), notice: 'Added reviews'
    else
      render :new
    end
  end

  # DELETE /reviews/1
  def destroy
    @review.destroy
    redirect_to request.referer, notice: 'Review was successfully deleted.'
  end

  private
    def require_ownership 
      if @review.user_id != session[:user_id]
        flash[:error] = "Can only edit your own review"
        redirect_to @review
      end
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_review
      @review = Review.find(params[:id])
    end

    def set_service
      @service = Service.find(params[:service_id])
    end

    # Only allow a list of trusted parameters through.
    def review_params
      params.require(:review).permit(:service_id, :user_id, :rating, :review)
    end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/_form.html.erb
<%= form_with(model: review, url: service_reviews_url(@service)) do |form| %>
  <br>
  <% if review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(review.errors.count, "error") %> prohibited this rating from being saved:</h2>

      <ul>
        <% review.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :rating, class: "control-label" %>
    <%= form.select :rating, [
        ["☆☆☆☆☆", "0"], 
        ["★☆☆☆☆", "1"], 
        ["★★☆☆☆", "2"], 
        ["★★★☆☆", "3"], 
        ["★★★★☆", "4"], 
        ["★★★★★", "5"]
      ], { :include_blank => true }, { class: "form-control" } %>
  </div>

  <div class="form-group">
    <%= form.label :review, class: "control-label" %>
    <%= form.text_area :review, placeholder: "Describe your experience...", class: "form-control" %>
  </div>

  <div class="actions text-center">
    <%= form.submit class: "btn btn-success" %>
  </div>
<% end %>

app/views/reviews/index.html.erb
<h1>Reviews</h1>

<div class="mx-auto text-center">
  <%= link_to 'Back', @service, class: "btn btn-secondary" %>
  <% if session[:user_id] != @service.user_id%>
    <% if session[:user_id] %>
      <%= link_to 'Create a review', new_service_review_path(@service), class: "btn btn-primary" %>
    <% else %>
      <%= link_to 'Login to create review', login_path, class: "btn btn-secondary" %>
    <% end %>
  <% end %>
</div>
<br>

<div class="reviews">
  <ul class="list-group">
    <% @reviews.each do |review| %>
      <li class="list-group-item">
        <div class="review">
          <div class="review-rating">
            <span><%= ("★" * review.rating) + ("☆" * (5 - review.rating)) %></span>            
          </div>
          <div class="review-title">
            <span><%= simple_format(review.review) %></span>
          </div>
          <div class="review-author-container">
            <span>Left by <span class="review-author"><%= review.user_name %></span></span>
          </div>
          <div class="review-created-at">
            <span><%= review.created_at%></span>
          </div>
        </div>
        <% if session[:user_id] == review.user_id  %>
          <div class="review-buttons">
            <%= link_to 'Delete Review', 
              service_review_path(@service, review),
              method: :delete, class: "btn btn-danger btn-sm btn-block",
              data: {confirm: 'Are you sure you want to delete this review?'} %>
          </div>
        <% end %>
      </li>
    <% end %>
  </ul>
  <div class="review-nav">
    <%== pagy_bootstrap_nav(@pagy) %>  
  </div>
</div>
<br>

app/views/reviews/new.html.erb
<h1>New Review</h1>

<div class="mx-auto text-center">
    <%= link_to 'Cancel', service_reviews_url(@service), class: "btn btn-secondary" %>
</div>

<div class='review-builder-container'>
    <%= render 'form', review: @review %>
</div>