config/routes.rb
Rails.application.routes.draw do
  resources :services do 
    resources :reviews
    resources :appointments
  end

  root to: 'services#index'

  get "/appointments" => "appointments#index"

  get '/register' => 'users#new'
  post '/register' => 'users#create'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'

  delete "/logout" => 'sessions#destroy'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <nav class="navbar navbar-dark bg-dark">
      <a class="navbar-brand" href="/">
        Ceasars in Athens
      </a>

      <%# make navbar dynamic for users and service providers %>
      <div class="ml-auto">
        <% if current_user  %>
          <h5 class="navbar-text nav-item mr-3 text-white" >
          <%= current_user.username %>
          </h5>
        <% end %>
        <% if current_user  %>
          <a class="navbar-text nav-item mr-3 text-white" href="/services?owned=true"> My Services </a>        
          <a class="navbar-text nav-item mr-3 text-white" href="/appointments"> My Appointments </a>
          <%= link_to 'Logout', logout_path, method: :delete, class: "navbar-text nav-item mr-3 text-white" %>
        <% else %>
          <%= link_to 'Login', login_path, class: "navbar-text nav-item mr-3 text-white" %>
        <% end %>
      </div>
    </nav>
    <% flash.each do |key, value| %>
      <div class="<%= flash_class(key) %>">
        <%= value %>
      </div>
    <% end %>    
    <%= yield %>
  </body>
</html>